# Generated by Django 4.2.7 on 2023-12-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='name',
            new_name='user',
        ),
    ]
